ame: Maven Package

on:
  release:
    types: [push]

jobs:
  build:

    runs-on: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup Github Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>gh</id><username>$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')</username><password>\${env.GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Netty in Centos 6 (needed for old libc compat)
        if: startsWith(matrix.os,'ubuntu')
        run: |
          docker build -f docker/Dockerfile-netty-centos6 -t netty-centos6 .
          REPO="gh::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}"
          docker run -t -v ~/.m2:/root/.m2 -v `pwd`:/code -w /code --entrypoint="" netty-centos6 bash -ic "mvn -B clean deploy -Partifactory -DskipTests -DaltDeploymentRepository=\"${REPO}\" -DaltSnapshotDeploymentRepository=\"${REPO}\""

      - name: Netty for osx (needed for kqueue lib)
        if: startsWith(matrix.os,'macos')
        run: |
          REPO="gh::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}"
          mvn -B clean -DskipTests
          mvn -B -U -pl transport-native-unix-common,transport-native-kqueue -Partifactory deploy -DskipTests -DaltDeploymentRepository="${REPO}" -DaltSnapshotDeploymentRepository="${REPO}"


